apiVersion: v1
kind: ConfigMap
metadata:
  name: phishing-quest-config
  labels:
    app: phishing-quest
data:
  config.yaml: |
    app:
      name: LabSC - Phishing Quest
      version: v0.0.3
    logger:
      level: info
      encoding: console
    http:
      enabled: true
      port: 8080
    db:
      enabled: true
      type: postgres
      showsql: false
      schema: phishing_quest
      connectionstring: "host=phishing-quest-postgresql.default.svc.cluster.local user=${DB_USER} password=${DB_PASSWORD} dbname=phishing_quest port=5432 sslmode=disable TimeZone=UTC connect_timeout=10"
