apiVersion: v1
kind: ConfigMap
metadata:
  name: phishing-quest-config
  labels:
    app: phishing-quest
data:
  config.yaml: |
    app:
      name: LabSC - Phishing Quest
      version: v0.0.3
    logger:
      level: info
      encoding: console #console or json
    http:
      enabled: true
      port: 8080
    db:
      enabled: true
      type: postgres
      showsql: false
      schema: capital
      connectionstring: "host=phishing-quest.cxyy0wwccs4r.sa-east-1.rds.amazonaws.com user=labsc password=phishingquest2024 dbname=postgres port=5432 sslmode=require TimeZone=UTC connect_timeout=10"
