apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-quest-deployment
  labels:
    app: phishing-quest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-quest
  template:
    metadata:
      labels:
        app: phishing-quest
    spec:
      containers:
        - name: phishing-quest
          image: loganncardoso/phishing-quest:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_PASSWORD
          envFrom:
            - configMapRef:
                name: phishing-quest-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-vol
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: config-vol
          configMap:
            name: phishing-quest-config
            optional: true