apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-quest-deployment
  labels:
    app: phishing-quest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-quest
  template:
    metadata:
      labels:
        app: phishing-quest
    spec:
      containers:
        - name: phishing-quest
          image: loganncardoso/phishing-quest:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: DB_HOST
              value: "phishing-quest-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "phishing_quest"
            - name: DB_SSLMODE
              value: "disable"
            - name: DB_TIMEZONE
              value: "UTC"
            - name: DB_CONNECT_TIMEOUT
              value: "5"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080
