apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishing-quest-deployment
  labels:
    app: phishing-quest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishing-quest
  template:
    metadata:
      labels:
        app: phishing-quest
    spec:
      containers:
        - name: phishing-quest
          image: loganncardoso/phishing-quest:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          env:
            - name: DB_HOST
              value: "phishing-quest-postgresql"  # Service name for PostgreSQL
            - name: DB_PORT
              value: "5432"  # Default PostgreSQL port
            - name: DB_NAME
              value: "phishing_quest"  # Database name
            - name: DB_SSLMODE
              value: "disable"  # Adjust if SSL is required
            - name: DB_TIMEZONE
              value: "UTC"  # Database timezone
            - name: DB_CONNECT_TIMEOUT
              value: "5"  # Connection timeout
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_USER  # Ensure this key exists in the secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phishing-quest-db-secret
                  key: DB_PASSWORD  # Ensure this key exists in the secret
          ports:
            - containerPort: 8080  # Port where your application listens
