apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  activeDeadlineSeconds: 1800  # Define um tempo limite de 30 minutos
  backoffLimit: 4  # Tenta o Job até 4 vezes em caso de falha
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:6.3.1
          args:
            - -configFiles=/flyway/conf/flyway.config
            - -locations=filesystem:/flyway/sql
            - migrate
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
            - name: flyway-config
              mountPath: /flyway/conf
      volumes:
        - name: flyway-sql
          configMap:
            name: flyway-sql-configmap  # Nome do ConfigMap que contém os scripts SQL
        - name: flyway-config
          secret:
            secretName: flyway-config-secret  # Nome do Secret que contém o arquivo flyway.config
      restartPolicy: OnFailure
