apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migration-job
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:6.3.1
          args:
            - -configFiles=/flyway/conf/flyway.config
            - -locations=filesystem:/flyway/sql
            - -connectRetries=60
            - migrate
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
            - name: flyway-config
              mountPath: /flyway/conf
      volumes:
        - name: flyway-sql
          configMap:
            name: flyway-sql-configmap
        - name: flyway-config
          secret:
            secretName: flyway-config-secret
      restartPolicy: OnFailure