version: '3.7'
services:
  phishing-quest-postgresql:
    image: postgres:16.4
    container_name: phishing-quest-postgresql
    environment:
      POSTGRES_DB: phishing_quest
      POSTGRES_USER: labsc
      POSTGRES_PASSWORD: phishingquest
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    networks:
      - phishing-quest-network

  phishing-quest-flyway-phishing-quest:
    image: flyway/flyway:6.3.1
    container_name: phishingquest-flyway-phishing-quest
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./../migrate/changelogs:/flyway/sql
      - ./../migrate/flyway.config:/flyway/conf/flyway.config
    networks:
      - phishing-quest-network

  phishing-quest-api:
    build: .
    container_name: phishing-quest-api
    ports:
      - "8080:8080"
    networks:
      - phishing-quest-network
    depends_on:
      - phishing-quest-postgresql
      - phishing-quest-flyway-phishing-quest

networks:
  phishing-quest-network:
    driver: bridge
    name: phishing-quest-network
