steps:
  - name: Bump version and create tag
    id: bump_version
    shell: pwsh
    run: |
      $versionType = "${{ github.event.inputs.version_type }}"
      $currentVersion = (git describe --tags $(git rev-list --tags --max-count=1) 2>$null) -replace 'v', ''
      if (-not $currentVersion) {
        $currentVersion = "0.0.0"
      }
      Write-Host "Current version: $currentVersion"

      $versionParts = $currentVersion -split '\.'
      $major = [int]$versionParts[0]
      $minor = [int]$versionParts[1]
      $patch = [int]$versionParts[2]

      switch ($versionType) {
        "major" {
          $major++
          $minor = 0
          $patch = 0
        }
        "minor" {
          $minor++
          $patch = 0
        }
        "patch" {
          $patch++
        }
        default {
          Write-Error "Invalid version type: $versionType"
          exit 1
        }
      }

      $newVersion = "v$major.$minor.$patch"
      Write-Host "New version: $newVersion"

      if (git rev-parse $newVersion 2>$null) {
        Write-Error "Tag $newVersion already exists."
        exit 1
      }

      git tag -a $newVersion -m "Version $newVersion"
      git push origin $newVersion

      echo "new_version=$newVersion" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
