name: Continuous Integration 
run-name: ${{ github.actor }} is running CI for Phishing Quest API 🛡️

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: |
            go.sum

      - name: Run Go version, Go mod tidy and tests
        run: |
          go version
          go mod tidy
          go test ./tests -v

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Docker image
        run: docker build -t loganncardoso/phishing-quest:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push loganncardoso/phishing-quest:${{ github.sha }}
