name: Continuous Integration

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: |
            go.sum

      - name: Run Go version and Go mod tidy
        run: |
          go version
          go mod tidy

      - name: Run tests
        run: go test ./tests -v

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t loganncardoso/phishing-quest:latest .

      - name: Push Docker image to Docker Hub
        run: docker push loganncardoso/phishing-quest:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy PVC for Postgres
        run: kubectl apply -f ./kubernetes/prod/postgres-pvc.yaml

      - name: Deploy Postgres Database
        run: |
          kubectl apply -f ./kubernetes/prod/postgres-deployment.yaml
          kubectl apply -f ./kubernetes/prod/postgres-service.yaml
          kubectl rollout status deployment/phishing-quest-postgresql

      - name: Apply Kubernetes configurations
        run: |
          kubectl apply -f ./kubernetes/prod/configmap.yaml
          kubectl apply -f ./kubernetes/prod/deployment.yaml
          kubectl apply -f ./kubernetes/prod/service.yaml
          kubectl apply -f ./kubernetes/prod/ingress.yaml

      - name: Wait for application rollout
        run: |
          kubectl rollout status deployment/phishing-quest-deployment

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/migrate/changelogs:/flyway/sql \
            -v ${{ github.workspace }}/migrate/flyway.conf:/flyway/conf/flyway.conf \
            flyway/flyway:6.3.1 migrate