name: Continuous Integration 
run-name: ${{ github.actor }} is running CI for Phishing Quest API 🛡️

on:
  pull_request:
    branches:
      - 'main'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: |
            go.sum

      - name: Run Go version, Go mod tidy and tests
        run: |
          go version
          go mod tidy
          go test ./tests -v
