name: Continuous Integration

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache-dependency-path: |
            go.sum

      - name: Run Go version and Go mod tidy
        run: |
          go version
          go mod tidy

      - name: Run tests
        run: go test ./tests -v

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t loganncardoso/phishing-quest:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push loganncardoso/phishing-quest:${{ env.IMAGE_TAG }}

      - name: Set up kubectl
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            # Instalação para Windows
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            Invoke-WebRequest -Uri "https://dl.k8s.io/release/v1.28.0/bin/windows/amd64/kubectl.exe" -OutFile "$env:USERPROFILE\kubectl.exe"
            $env:Path += ";$env:USERPROFILE"
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            # Instalação para Linux
            curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # Instalação para macOS
            curl -LO "https://dl.k8s.io/release/v1.28.0/bin/darwin/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          fi

      - name: Configure kubeconfig
        run: |
          if (!(Test-Path -Path "$HOME\.kube")) {
            New-Item -ItemType Directory -Force -Path "$HOME\.kube"
          }
          $KubeConfigContent = "${{ secrets.KUBE_CONFIG }}"
          $KubeConfigContent | Out-File -FilePath "$HOME\.kube\config" -Encoding ascii

          # Ajustar permissões no Windows
          $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
          $acl = Get-Acl "$HOME\.kube\config"
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($currentUser, "FullControl", "Allow")
          $acl.SetAccessRule($accessRule)
          Set-Acl "$HOME\.kube\config" $acl

      - name: Test Kubernetes connection
        run: kubectl get nodes

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f ./kubernetes/prod/ --recursive
          kubectl set image deployment/phishing-quest-deployment phishing-quest=loganncardoso/phishing-quest:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/phishing-quest-deployment || exit 0

      - name: Verify migrate directory contents
        run: |
          echo "Listing contents of migrate directory:"
          Get-ChildItem -Path "${{ github.workspace }}/migrate" -Recurse
        shell: pwsh