name: Continuous Deployment

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Commit SHA for Tag
        id: get_sha
        run: echo "IMAGE_TAG=$(git rev-list -n 1 ${{ github.ref_name }})" >> $GITHUB_ENV

      - name: Set up kubectl
        run: |
          if (!(Test-Path -Path "$HOME\.kube")) {
            New-Item -ItemType Directory -Force -Path "$HOME\.kube"
          }
          $KubeConfigContent = "${{ secrets.KUBE_CONFIG }}"
          $KubeConfigContent | Out-File -FilePath "$HOME\.kube\config" -Encoding ascii

          # Ajustar permissões no Windows
          $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
          $acl = Get-Acl "$HOME\.kube\config"
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($currentUser, "FullControl", "Allow")
          $acl.SetAccessRule($accessRule)
          Set-Acl "$HOME\.kube\config" $acl

      - name: Test Kubernetes connection
        run: kubectl get nodes

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f ./kubernetes/prod/ --recursive
          kubectl set image deployment/phishing-quest-deployment phishing-quest=loganncardoso/phishing-quest:${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/phishing-quest-deployment